#!/bin/sh

git diff --name-only --cached --diff-filter=d | xargs bun run format
git diff --name-only --cached --diff-filter=d | xargs bun run lint
git diff --name-only --cached --diff-filter=d | xargs git add
